name: CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check PHP Version
        run: php -v

      - name: Run Testing
        run: echo "Testing berhasil"

      - name: Build Docker Image
        run: docker build -t uts-devops-app .

      - name: Simulasi Deploy ke Staging
        run: echo "Deployment ke staging berhasil"
